title: Junkai Li's Homepage
page-top-title: Junkai Li
top-section-bg-text: Quantum & Finance
home-subtitle: Junkai Li&ensp;|&ensp;李钧楷
copyright-text: '&copy; Junkai Li 2023-2024. All Rights Reserved.'
